#!/usr/bin/env python3
"""Generate the path the install dashboard's snake draws the Omarchy mark along.

A snake one cell wide cannot cover the mark: its T-junctions rule out any
single non-crossing path. At twice the resolution it always can. Take a
spanning tree of the mark's cells, give each cell a 2x2 loop, and splice
neighbouring loops together along every tree edge; the result is one
Hamiltonian cycle whose cells are exactly the mark at 2x. The snake walks it,
so at full length its body is the mark.

The dashboard reads the committed output; nothing is generated at install
time. Rerun after changing MARK:

    builder/generate-snake-path.py > configs/airootfs/usr/share/omarchy-iso/snake-path
"""

import sys

# The Omarchy mark on its 80-unit design grid, 15x15, '#' filled. The square
# mark is not shipped as an SVG anywhere the ISO can see (omarchy-settings'
# logo.svg is the wordmark), so this grid is the source of truth.
MARK = """
###############
#......#......#
#.######...##.#
#.#.........#.#
#.#.........#.#
#.#.........#.#
#.#.........#.#
###.........#.#
#.#.........#.#
#.#.........#.#
#.#.........#.#
#.#.........#.#
#.###########.#
#......#......#
########.######
""".split()

# The stub beside the mouth, where the snake hatches.
STUB = (13, 7)
UP, RIGHT, DOWN, LEFT = (-1, 0), (0, 1), (1, 0), (0, -1)
TURN_ORDER = (RIGHT, DOWN, LEFT, UP)
# Bottom-left fine cell of the stub.
START = (2 * STUB[0] + 1, 2 * STUB[1])


def mark_cells():
    return {(r, c) for r, row in enumerate(MARK) for c, ch in enumerate(row) if ch == "#"}


def spanning_tree(cells):
    """Depth-first from STUB, heading up; keep heading, else turn in TURN_ORDER."""
    seen = {STUB}
    edges = []
    stack = [(STUB, UP)]
    # Iterative with explicit per-node direction queues so the visit order is
    # exactly that of the recursive definition.
    queues = {STUB: [UP] + [d for d in TURN_ORDER if d != UP]}
    while stack:
        cell, _ = stack[-1]
        queue = queues[cell]
        while queue:
            d = queue.pop(0)
            nxt = (cell[0] + d[0], cell[1] + d[1])
            if nxt in cells and nxt not in seen:
                seen.add(nxt)
                edges.append((cell, nxt))
                queues[nxt] = [d] + [t for t in TURN_ORDER if t != d]
                stack.append((nxt, d))
                break
        else:
            stack.pop()
    assert seen == cells, "mark is not connected"
    return edges


def hamiltonian_cycle(cells, edges):
    adj = {}

    def link(a, b):
        adj.setdefault(a, set()).add(b)
        adj.setdefault(b, set()).add(a)

    def unlink(a, b):
        adj[a].remove(b)
        adj[b].remove(a)

    for r, c in cells:
        tl, tr, br, bl = (2 * r, 2 * c), (2 * r, 2 * c + 1), (2 * r + 1, 2 * c + 1), (2 * r + 1, 2 * c)
        link(tl, tr); link(tr, br); link(br, bl); link(bl, tl)

    for p, q in edges:
        p, q = min(p, q), max(p, q)
        if p[0] == q[0]:
            # p left of q: open p's right side and q's left side, bridge across.
            row, a, b = 2 * p[0], 2 * p[1] + 1, 2 * q[1]
            unlink((row, a), (row + 1, a)); unlink((row, b), (row + 1, b))
            link((row, a), (row, b)); link((row + 1, a), (row + 1, b))
        else:
            # p above q: open p's bottom and q's top, bridge down.
            col, a, b = 2 * p[1], 2 * p[0] + 1, 2 * q[0]
            unlink((a, col), (a, col + 1)); unlink((b, col), (b, col + 1))
            link((a, col), (b, col)); link((a, col + 1), (b, col + 1))

    assert all(len(n) == 2 for n in adj.values()), "not a 2-regular graph"

    first = [n for n in adj[START] if n[0] < START[0]]
    assert len(first) == 1, "START must have exactly one upward neighbour"
    path = [START, first[0]]
    while True:
        prev, here = path[-2], path[-1]
        nxt = next(n for n in adj[here] if n != prev)
        if nxt == START:
            return path
        path.append(nxt)


def build_path():
    cells = mark_cells()
    edges = spanning_tree(cells)
    path = hamiltonian_cycle(cells, edges)

    fine = {(2 * r + i, 2 * c + j) for r, c in cells for i in (0, 1) for j in (0, 1)}
    assert len(path) == 4 * len(cells) == 380, f"expected 380 cells, got {len(path)}"
    assert len(set(path)) == len(path), "path revisits a cell"
    for a, b in zip(path, path[1:] + path[:1]):
        assert abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1, f"{a} -> {b} is not a step"
    assert set(path) == fine, "path cells differ from the mark at 2x"
    return path


def main():
    path = build_path()
    out = sys.stdout
    out.write("# Generated by builder/generate-snake-path.py; do not edit.\n")
    out.write("# Omarchy mark at 2x (30x30 cells), one 'row col' per line, in snake order.\n")
    for r, c in path:
        out.write(f"{r} {c}\n")


if __name__ == "__main__":
    main()
